# Generated by Django 3.0 on 2019-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_event_type', models.CharField(max_length=30)),
                ('task_start_program_time', models.TimeField()),
                ('task_start_actual_time', models.TimeField()),
                ('number_of_servers_running', models.CharField(max_length=10)),
                ('clock_wall_color', models.CharField(max_length=50)),
                ('clock_face_color', models.CharField(max_length=50)),
                ('clock_hand_color', models.CharField(max_length=50)),
            ],
        ),
    ]
